/** Gestión de asignaciones sacerdotales con Supabase y permisos de Administrador. */
import { hasPermission, supabase } from './auth.js';

const PAGE_SIZE = 10;
let assignments = [], priests = [], parishes = [], positions = [], context, elements, formModal, detailModal, finishModal, warningModal, toast, events, editingId = null, editingAssignment = null, pendingFinish = null, warningAction = null, currentPage = 1;

/** Retorna la fecha local en formato ISO para comparar estados de asignación. */
const today = () => {
  const date = new Date();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  return `${date.getFullYear()}-${month}-${day}`;
};
/** Convierte texto vacío en null para las columnas opcionales. */
const optional = (value) => value.trim() || null;
/** Formatea fechas sin insertar contenido no confiable como HTML. */
const formatDate = (value, time = false) => value ? new Intl.DateTimeFormat('es-GT', time ? { dateStyle: 'medium', timeStyle: 'short' } : { dateStyle: 'medium' }).format(new Date(value)) : '—';
/** Determina el estado calculado de una asignación. */
const assignmentStatus = (assignment) => assignment.fecha_inicio > today() ? 'Próxima' : assignment.fecha_fin && assignment.fecha_fin < today() ? 'Finalizada' : 'Vigente';
/** Verifica que Bootstrap Bundle esté disponible en el Dashboard principal. */
const getBootstrap = () => { if (!window.bootstrap?.Modal || !window.bootstrap?.Toast) throw new Error('Bootstrap JavaScript no está disponible.'); return window.bootstrap; };
/** Mueve modales y toast al body para evitar que el área dinámica limite su visualización. */
const mountOverlays = () => [document.querySelector('#assignment-modal'), document.querySelector('#assignment-detail-modal'), document.querySelector('#assignment-finish-modal'), document.querySelector('#assignment-warning-modal'), document.querySelector('#assignment-toast')?.closest('.toast-container')].filter(Boolean).forEach((node) => { node.dataset.viewOverlay = 'asignaciones'; document.body.append(node); });
/** Obtiene todos los nodos del módulo tras insertar su template. */
const cache = () => ({ form: document.querySelector('#assignment-form'), priest: document.querySelector('#assignment-priest'), parish: document.querySelector('#assignment-parish'), position: document.querySelector('#assignment-position'), start: document.querySelector('#assignment-start'), end: document.querySelector('#assignment-end'), search: document.querySelector('#assignment-search'), priestFilter: document.querySelector('#assignment-priest-filter'), parishFilter: document.querySelector('#assignment-parish-filter'), positionFilter: document.querySelector('#assignment-position-filter'), statusFilter: document.querySelector('#assignment-status-filter'), table: document.querySelector('#assignment-table-body'), wrapper: document.querySelector('#assignment-table-wrapper'), loader: document.querySelector('#assignment-loader'), empty: document.querySelector('#assignment-empty-state'), emptyText: document.querySelector('#assignment-empty-state p'), count: document.querySelector('#assignment-count'), pagination: document.querySelector('#assignment-pagination'), error: document.querySelector('#assignment-error'), title: document.querySelector('#assignment-modal-title'), save: document.querySelector('#save-assignment-button'), detail: document.querySelector('#assignment-detail-content'), finishDate: document.querySelector('#assignment-finish-date'), finishNotes: document.querySelector('#assignment-finish-notes'), finishMessage: document.querySelector('#assignment-finish-message'), finishError: document.querySelector('#assignment-finish-error'), confirmFinish: document.querySelector('#confirm-assignment-finish-button'), warningTitle: document.querySelector('#assignment-warning-title'), warningMessage: document.querySelector('#assignment-warning-message'), confirmWarning: document.querySelector('#confirm-assignment-warning-button'), toastMessage: document.querySelector('#assignment-toast-message'), toastIcon: document.querySelector('#assignment-toast-icon') });
/** Muestra un mensaje de error de Bootstrap Alert. */
const showError = (message) => { elements.error.textContent = message; elements.error.classList.remove('d-none'); };
/** Oculta el Alert principal. */
const hideError = () => { elements.error.textContent = ''; elements.error.classList.add('d-none'); };
/** Muestra un Toast Bootstrap de éxito o error. */
const showToast = (message, success = true) => { elements.toastMessage.textContent = message; elements.toastIcon.className = `bi ${success ? 'bi-check-circle-fill' : 'bi-exclamation-circle-fill'}`; toast.show(); };
/** Traduce errores de datos a textos seguros para la interfaz. */
const errorMessage = (error) => { if (error?.code === '23505') return 'Ya existe una asignación con esos datos.'; if (error?.code === '23503') return 'Uno de los registros relacionados ya no está disponible.'; if (error?.code === '42501') return 'No cuenta con permisos para realizar esta operación.'; if (error?.name === 'AbortError') return 'La consulta tardó demasiado. Intente nuevamente.'; if (error instanceof TypeError) return 'No fue posible conectar con el servidor.'; return 'No fue posible completar la operación. Intente nuevamente.'; };
/** Carga opciones activas del formulario y de los filtros. */
const loadCatalogs = async () => {
  const [priestResult, parishResult, positionResult] = await Promise.all([
    supabase.from('sacerdotes').select('id,codigo,nombres,apellidos').eq('activo', true).order('apellidos', { ascending: true }).order('nombres', { ascending: true }),
    supabase.from('parroquias').select('id,codigo,nombre,municipio').eq('estado', true).order('nombre', { ascending: true }),
    supabase.from('cargos_sacerdotales').select('id,nombre,descripcion').eq('activo', true).order('nombre', { ascending: true }),
  ]);
  [priestResult, parishResult, positionResult].forEach((result) => { if (result.error) throw result.error; }); priests = priestResult.data ?? []; parishes = parishResult.data ?? []; positions = positionResult.data ?? []; populateSelects();
};
/** Inserta opciones de selects usando DOM seguro. */
const populate = (select, values, label, selected = '') => { select.replaceChildren(new Option(select.dataset.placeholder || 'Todos', '')); values.forEach((value) => select.add(new Option(label(value), value.id))); select.value = selected; };
/** Alimenta selects del formulario y filtros preservando su selección. */
const populateSelects = () => {
  const values = { priest: elements.priest.value, parish: elements.parish.value, position: elements.position.value, priestFilter: elements.priestFilter.value, parishFilter: elements.parishFilter.value, positionFilter: elements.positionFilter.value };
  elements.priest.dataset.placeholder = 'Seleccione un sacerdote'; elements.parish.dataset.placeholder = 'Seleccione una parroquia'; elements.position.dataset.placeholder = 'Seleccione un cargo'; elements.priestFilter.dataset.placeholder = 'Todos los sacerdotes'; elements.parishFilter.dataset.placeholder = 'Todas las parroquias'; elements.positionFilter.dataset.placeholder = 'Todos los cargos';
  const priestLabel = (value) => `${value.codigo} · ${[value.nombres, value.apellidos].filter(Boolean).join(' ')}`; const parishLabel = (value) => `${value.codigo} · ${value.nombre}`;
  populate(elements.priest, priests, priestLabel, values.priest); populate(elements.priestFilter, priests, priestLabel, values.priestFilter); populate(elements.parish, parishes, parishLabel, values.parish); populate(elements.parishFilter, parishes, parishLabel, values.parishFilter); populate(elements.position, positions, (value) => value.nombre, values.position); populate(elements.positionFilter, positions, (value) => value.nombre, values.positionFilter);
};
/** Normaliza la respuesta de la vista o la consulta relacional de respaldo. */
const normalizeAssignment = (record) => ({ ...record, sacerdote: record.sacerdote ?? [record.sacerdotes?.nombres, record.sacerdotes?.apellidos].filter(Boolean).join(' '), sacerdote_codigo: record.sacerdote_codigo ?? record.sacerdotes?.codigo, parroquia: record.parroquia ?? record.parroquias?.nombre, parroquia_codigo: record.parroquia_codigo ?? record.parroquias?.codigo, municipio: record.municipio ?? record.parroquias?.municipio, cargo: record.cargo ?? record.cargos_sacerdotales?.nombre });
/** Consulta la vista de asignaciones y usa una consulta relacional cuando la vista no es accesible. */
const fetchAssignments = async () => {
  const primary = await supabase.from('v_asignaciones_sacerdotales').select('*').order('fecha_inicio', { ascending: false });
  if (!primary.error) return (primary.data ?? []).map(normalizeAssignment);
  console.warn('No fue posible consultar la vista de asignaciones; se usa la consulta relacional.', primary.error);
  const fallback = await supabase.from('asignaciones_sacerdotales').select('*,sacerdotes(codigo,nombres,apellidos),parroquias(codigo,nombre,municipio),cargos_sacerdotales(nombre)').order('fecha_inicio', { ascending: false });
  if (fallback.error) throw primary.error; return (fallback.data ?? []).map(normalizeAssignment);
};
/** Carga datos y siempre retira el loader al finalizar. */
const loadData = async () => { elements.loader.classList.remove('d-none'); elements.wrapper.classList.add('d-none'); elements.empty.classList.add('d-none'); hideError(); try { const [data] = await Promise.all([fetchAssignments(), loadCatalogs()]); assignments = data; currentPage = 1; render(); } catch (error) { console.error('No fue posible cargar las asignaciones:', error); assignments = []; elements.emptyText.textContent = 'No fue posible cargar las asignaciones.'; elements.empty.classList.remove('d-none'); showError(errorMessage(error)); } finally { elements.loader.classList.add('d-none'); } };
/** Filtra por texto y todos los filtros seleccionados en conjunto. */
const filtered = () => { const query = elements.search.value.trim().toLocaleLowerCase('es'); return assignments.filter((item) => { const matches = [item.sacerdote, item.sacerdote_codigo, item.parroquia, item.parroquia_codigo, item.municipio, item.cargo, item.numero_decreto].some((value) => value?.trim().toLocaleLowerCase('es').includes(query)); return matches && (!elements.priestFilter.value || item.sacerdote_id === elements.priestFilter.value) && (!elements.parishFilter.value || item.parroquia_id === elements.parishFilter.value) && (!elements.positionFilter.value || String(item.cargo_id) === elements.positionFilter.value) && (!elements.statusFilter.value || assignmentStatus(item) === elements.statusFilter.value); }); };
/** Crea una acción de tabla con icono Bootstrap y handler seguro. */
const actionButton = (icon, label, handler) => { const button = document.createElement('button'), image = document.createElement('i'); button.className = 'btn assignment-action-button'; button.type = 'button'; button.setAttribute('aria-label', label); image.className = `bi ${icon}`; image.setAttribute('aria-hidden', 'true'); button.append(image); button.addEventListener('click', handler); return button; };
/** Inserta una fila con acciones exclusivas de Administrador. */
const appendRow = (item) => { const row = document.createElement('tr'); [item.sacerdote || '—', item.parroquia || '—', item.cargo || '—', formatDate(item.fecha_inicio), formatDate(item.fecha_fin), item.numero_decreto || '—'].forEach((value, index) => { const cell = document.createElement('td'); cell.textContent = value; if (index === 0) cell.className = 'assignment-table__name'; row.append(cell); }); const state = assignmentStatus(item), stateCell = document.createElement('td'), badge = document.createElement('span'); badge.className = `assignment-status assignment-status--${state === 'Vigente' ? 'current' : state === 'Próxima' ? 'future' : 'finished'}`; badge.textContent = state; stateCell.append(badge); row.insertBefore(stateCell, row.children[5]); const actions = document.createElement('td'), group = document.createElement('div'); group.className = 'assignment-actions'; group.append(actionButton('bi-eye', `Ver asignación de ${item.sacerdote}`, () => openDetails(item))); group.append(actionButton('bi-pencil', `Editar asignación de ${item.sacerdote}`, () => openEdit(item))); if (state === 'Vigente') group.append(actionButton('bi-calendar-x', `Finalizar asignación de ${item.sacerdote}`, () => openFinish(item))); if (state === 'Finalizada') group.append(actionButton('bi-arrow-counterclockwise', `Reabrir asignación de ${item.sacerdote}`, () => openReopen(item))); actions.append(group); row.append(actions); elements.table.append(row); };
/** Renderiza contador, tabla, estado vacío y paginación local. */
const render = () => { const records = filtered(), pages = Math.max(1, Math.ceil(records.length / PAGE_SIZE)); currentPage = Math.min(currentPage, pages); elements.count.textContent = `${records.length} ${records.length === 1 ? 'registro' : 'registros'}`; elements.table.replaceChildren(); records.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE).forEach(appendRow); elements.wrapper.classList.toggle('d-none', records.length === 0); elements.empty.classList.toggle('d-none', records.length > 0); elements.pagination.replaceChildren(); elements.pagination.classList.toggle('d-none', pages <= 1); for (let page = 1; page <= pages; page += 1) { const button = document.createElement('button'); button.className = `assignment-pagination__button${page === currentPage ? ' is-active' : ''}`; button.type = 'button'; button.textContent = String(page); button.addEventListener('click', () => { currentPage = page; render(); }); elements.pagination.append(button); } };
/** Restablece el formulario a los valores de una nueva asignación. */
const resetForm = () => { editingId = null; editingAssignment = null; elements.form.reset(); elements.form.classList.remove('was-validated'); elements.start.value = today(); elements.title.textContent = 'Nueva asignación'; elements.save.querySelector('span').textContent = 'Guardar'; };
/** Abre el formulario de creación. */
const openNew = () => { if (!hasPermission(context, 'assignments.create')) return showToast('Acceso no autorizado.', false); resetForm(); formModal.show(); };
/** Precarga el formulario para editar una asignación existente. */
const openEdit = (item) => { if (!hasPermission(context, 'assignments.update')) return showToast('Acceso no autorizado.', false); editingId = item.id; editingAssignment = item; elements.form.reset(); Object.entries(item).forEach(([key, value]) => { const field = elements.form.elements.namedItem(key); if (field) field.value = value ?? ''; }); elements.title.textContent = 'Editar asignación'; elements.save.querySelector('span').textContent = 'Guardar cambios'; formModal.show(); };
/** Muestra el detalle sin exponer identificadores UUID. */
const openDetails = (item) => { const fields = [['Sacerdote', item.sacerdote], ['Código del sacerdote', item.sacerdote_codigo], ['Parroquia', item.parroquia], ['Código de parroquia', item.parroquia_codigo], ['Municipio', item.municipio], ['Cargo', item.cargo], ['Fecha de inicio', formatDate(item.fecha_inicio)], ['Fecha de finalización', formatDate(item.fecha_fin)], ['Estado', assignmentStatus(item)], ['Número de decreto', item.numero_decreto], ['Observaciones', item.observaciones], ['Fecha de registro', formatDate(item.created_at, true)], ['Última actualización', formatDate(item.updated_at, true)]]; elements.detail.replaceChildren(); const grid = document.createElement('dl'); grid.className = 'assignment-details__grid'; fields.forEach(([label, value]) => { const term = document.createElement('dt'), description = document.createElement('dd'); term.textContent = label; description.textContent = value || '—'; grid.append(term, description); }); elements.detail.append(grid); detailModal.show(); };
/** Abre el modal que registra la fecha y observación de finalización. */
const openFinish = (item) => { if (!hasPermission(context, 'assignments.finish')) return showToast('Acceso no autorizado.', false); pendingFinish = item; elements.finishDate.value = today(); elements.finishNotes.value = ''; elements.finishError.classList.add('d-none'); elements.finishMessage.textContent = `Finalizar la asignación de ${item.sacerdote} en ${item.parroquia}.`; finishModal.show(); };
/** Presenta una confirmación Bootstrap reutilizable y ejecuta una acción al aceptarla. */
const openWarning = (title, message, action) => { elements.warningTitle.textContent = title; elements.warningMessage.textContent = message; warningAction = action; warningModal.show(); };
/** Solicita confirmación antes de quitar una finalización registrada. */
const openReopen = (item) => openWarning('Reabrir asignación', `¿Desea reabrir la asignación de ${item.sacerdote}? La fecha de finalización se eliminará.`, async () => { const { error } = await supabase.from('asignaciones_sacerdotales').update({ fecha_fin: null }).eq('id', item.id).select().single(); if (error) throw error; await loadData(); showToast('Asignación reabierta correctamente.'); });
/** Genera un payload sin columnas de auditoría o claves administradas por base de datos. */
const buildPayload = () => { const form = new FormData(elements.form); return { sacerdote_id: form.get('sacerdote_id'), parroquia_id: form.get('parroquia_id'), cargo_id: Number(form.get('cargo_id')), fecha_inicio: form.get('fecha_inicio'), fecha_fin: form.get('fecha_fin') || null, numero_decreto: optional(form.get('numero_decreto')), observaciones: optional(form.get('observaciones')) }; };
/** Valida campos requeridos y rango de fechas. */
const validate = () => { if (!elements.form.checkValidity()) return 'Complete los campos obligatorios.'; if (elements.end.value && elements.end.value < elements.start.value) return 'La fecha de finalización no puede ser anterior a la fecha de inicio.'; return null; };
/** Consulta asignaciones vigentes del sacerdote sin impedir responsabilidades múltiples. */
const hasCurrentAssignments = async (priestId) => { const { data, error } = await supabase.from('asignaciones_sacerdotales').select('id').eq('sacerdote_id', priestId).lte('fecha_inicio', today()).or(`fecha_fin.is.null,fecha_fin.gte.${today()}`).neq('id', editingId || '00000000-0000-0000-0000-000000000000'); if (error) throw error; return (data ?? []).length > 0; };
/** Guarda la asignación luego de advertir, cuando corresponda, sobre otras vigentes. */
const save = async (event, confirmed = false) => { event?.preventDefault(); if (!hasPermission(context, editingId ? 'assignments.update' : 'assignments.create')) return showToast('Acceso no autorizado.', false); const validation = validate(); if (validation) { elements.form.classList.add('was-validated'); showError(validation); return; } const payload = buildPayload(); if (!confirmed && editingAssignment?.fecha_fin && !payload.fecha_fin) { openWarning('Reabrir asignación', 'La fecha de finalización se eliminará. ¿Desea reabrir esta asignación?', () => save(null, true)); return; } try { if (!confirmed && await hasCurrentAssignments(payload.sacerdote_id)) { openWarning('Asignaciones vigentes', 'Este sacerdote ya tiene una o más asignaciones vigentes. ¿Desea continuar?', () => save(null, true)); return; } } catch (error) { console.error('No fue posible verificar asignaciones vigentes:', error); showError(errorMessage(error)); showToast(errorMessage(error), false); return; } elements.save.disabled = true; elements.save.querySelector('.spinner-border').classList.remove('d-none'); hideError(); const editing = Boolean(editingId); try { const query = editing ? supabase.from('asignaciones_sacerdotales').update(payload).eq('id', editingId).select().single() : supabase.from('asignaciones_sacerdotales').insert(payload).select().single(); const { error } = await query; if (error) throw error; formModal.hide(); resetForm(); await loadData(); showToast(editing ? 'Asignación actualizada correctamente.' : 'Asignación registrada correctamente.'); } catch (error) { console.error('No fue posible guardar la asignación:', error); showError(errorMessage(error)); showToast(errorMessage(error), false); } finally { elements.save.disabled = false; elements.save.querySelector('.spinner-border').classList.add('d-none'); } };
/** Finaliza una asignación vigente conservando el historial. */
const finish = async () => { if (!pendingFinish || !hasPermission(context, 'assignments.finish')) return showToast('Acceso no autorizado.', false); if (!elements.finishDate.value || elements.finishDate.value < pendingFinish.fecha_inicio) { elements.finishError.textContent = 'Indique una fecha de finalización posterior o igual a la fecha de inicio.'; elements.finishError.classList.remove('d-none'); return; } elements.confirmFinish.disabled = true; elements.confirmFinish.querySelector('.spinner-border').classList.remove('d-none'); try { const notes = optional(elements.finishNotes.value); const observations = notes ? [pendingFinish.observaciones, notes].filter(Boolean).join('\n') : pendingFinish.observaciones || null; const { error } = await supabase.from('asignaciones_sacerdotales').update({ fecha_fin: elements.finishDate.value, observaciones }).eq('id', pendingFinish.id).select().single(); if (error) throw error; finishModal.hide(); await loadData(); showToast('Asignación finalizada correctamente.'); } catch (error) { console.error('No fue posible finalizar la asignación:', error); showError(errorMessage(error)); showToast(errorMessage(error), false); } finally { pendingFinish = null; elements.confirmFinish.disabled = false; elements.confirmFinish.querySelector('.spinner-border').classList.add('d-none'); } };
/** Inicializa el módulo una vez que app.js colocó su template en el DOM. */
export async function initAsignaciones(userContext) { if (!userContext || !hasPermission(userContext, 'assignments.view')) return; destroyAsignaciones(); context = userContext; mountOverlays(); elements = cache(); const bootstrap = getBootstrap(); formModal = bootstrap.Modal.getOrCreateInstance(document.getElementById('assignment-modal')); detailModal = bootstrap.Modal.getOrCreateInstance(document.getElementById('assignment-detail-modal')); finishModal = bootstrap.Modal.getOrCreateInstance(document.getElementById('assignment-finish-modal')); warningModal = bootstrap.Modal.getOrCreateInstance(document.getElementById('assignment-warning-modal')); toast = bootstrap.Toast.getOrCreateInstance(document.getElementById('assignment-toast')); events = new AbortController(); const options = { signal: events.signal }; document.querySelector('#new-assignment-button').addEventListener('click', openNew, options); elements.form.addEventListener('submit', save, options); [elements.search, elements.priestFilter, elements.parishFilter, elements.positionFilter, elements.statusFilter].forEach((control) => control.addEventListener(control === elements.search ? 'input' : 'change', () => { currentPage = 1; render(); }, options)); elements.confirmFinish.addEventListener('click', finish, options); elements.confirmWarning.addEventListener('click', async () => { const action = warningAction; warningAction = null; warningModal.hide(); try { await action?.(); } catch (error) { console.error('No fue posible completar la operación confirmada:', error); showError(errorMessage(error)); showToast(errorMessage(error), false); } }, options); await loadData(); }
/** Libera eventos, instancias Bootstrap y overlays al cambiar de módulo. */
export const destroyAsignaciones = () => { events?.abort(); events = null; [formModal, detailModal, finishModal, warningModal, toast].forEach((instance) => instance?.dispose()); formModal = detailModal = finishModal = warningModal = toast = null; document.querySelectorAll('[data-view-overlay="asignaciones"]').forEach((node) => node.remove()); };
