/** CRUD de Comunidades con filtros, permisos de interfaz y Supabase. */
import { hasPermission, supabase } from './auth.js';
const PAGE_SIZE=10; let communities=[],parishes=[],context,e,formModal,detailModal,statusModal,toast,events,editingId=null,pending=null,page=1;
const optional=(v)=>v.trim()||null; const date=(v,time=false)=>v?new Intl.DateTimeFormat('es-GT',time?{dateStyle:'medium',timeStyle:'short'}:{dateStyle:'medium'}).format(new Date(v)):'—';
const bootstrap=()=>{if(!window.bootstrap?.Modal||!window.bootstrap?.Toast)throw new Error('Bootstrap JavaScript no está disponible.');return window.bootstrap};
/** Mueve overlays al body para Bootstrap. */const mount=()=>[document.querySelector('#community-modal'),document.querySelector('#community-detail-modal'),document.querySelector('#community-status-modal'),document.querySelector('#community-toast')?.closest('.toast-container')].filter(Boolean).forEach(n=>{n.dataset.viewOverlay='comunidades';document.body.append(n)});
/** Obtiene referencias DOM tras insertar el template. */const cache=()=>({form:document.querySelector('#community-form'),code:document.querySelector('#community-code'),parish:document.querySelector('#community-parish'),municipality:document.querySelector('#community-municipality'),search:document.querySelector('#community-search'),parishFilter:document.querySelector('#community-parish-filter'),typeFilter:document.querySelector('#community-type-filter'),municipalityFilter:document.querySelector('#community-municipality-filter'),statusFilter:document.querySelector('#community-status-filter'),table:document.querySelector('#community-table-body'),wrapper:document.querySelector('#community-table-wrapper'),loader:document.querySelector('#community-loader'),empty:document.querySelector('#community-empty'),emptyText:document.querySelector('#community-empty p'),count:document.querySelector('#community-count'),pagination:document.querySelector('#community-pagination'),error:document.querySelector('#community-error'),title:document.querySelector('#community-modal-title'),save:document.querySelector('#save-community-button'),detail:document.querySelector('#community-detail'),statusTitle:document.querySelector('#community-status-title'),statusMessage:document.querySelector('#community-status-message'),confirm:document.querySelector('#confirm-community-status'),toastMessage:document.querySelector('#community-toast-message'),toastIcon:document.querySelector('#community-toast-icon')});
const errorText=(x)=>x?.code==='23505'?'No fue posible generar un código único o ya existe una comunidad con datos repetidos en esta parroquia.':x?.code==='23503'?'La parroquia seleccionada no está disponible.':x?.code==='42501'?'No cuenta con permisos para realizar esta operación.':x instanceof TypeError?'No fue posible conectar con el servidor.':'No fue posible completar la operación. Intente nuevamente.';
const showError=(m)=>{e.error.textContent=m;e.error.classList.remove('d-none')};const hideError=()=>{e.error.textContent='';e.error.classList.add('d-none')};const showToast=(m,ok=true)=>{e.toastMessage.textContent=m;e.toastIcon.className=`bi ${ok?'bi-check-circle-fill':'bi-exclamation-circle-fill'}`;toast.show()};
/** Alterna el aviso de creación y el código generado no editable. */const codeMode=(codigo=null)=>{const hasCode=Boolean(codigo);e.code.value=codigo??'';e.code.classList.toggle('d-none',!hasCode);document.querySelector('#community-code-auto-note').classList.toggle('d-none',hasCode)};
/** Carga parroquias activas para formulario y filtro. */const loadParishes=async()=>{const {data,error}=await supabase.from('parroquias').select('id,codigo,nombre,municipio').eq('estado',true).order('nombre',{ascending:true});if(error)throw error;parishes=data??[];const current=e.parish.value;[e.parish,e.parishFilter].forEach((select,index)=>{select.replaceChildren(new Option(index?'Todas las parroquias':'Seleccione una parroquia',''));parishes.forEach(p=>select.add(new Option(`${p.codigo} · ${p.nombre}`,p.id)))});e.parish.value=current};
/** Consulta vista de comunidades y aplica respaldo relacional si la vista no está permitida. */const fetchCommunities=async()=>{const view=await supabase.from('v_comunidades').select('*').order('parroquia',{ascending:true}).order('nombre',{ascending:true});if(!view.error)return view.data??[];console.warn('Vista v_comunidades no disponible; se usa respaldo relacional.',view.error);const fallback=await supabase.from('comunidades').select('*,parroquias(codigo,nombre,municipio)').order('nombre',{ascending:true});if(fallback.error)throw view.error;return(fallback.data??[]).map(x=>({...x,parroquia:x.parroquia??x.parroquias?.nombre,parroquia_codigo:x.parroquia_codigo??x.parroquias?.codigo,parroquia_municipio:x.parroquia_municipio??x.parroquias?.municipio}))};
/** Llena filtro de municipios desde las comunidades cargadas. */const municipalities=()=>{const old=e.municipalityFilter.value;e.municipalityFilter.replaceChildren(new Option('Todos los municipios',''));[...new Set(communities.map(x=>x.municipio).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es')).forEach(x=>e.municipalityFilter.add(new Option(x,x)));e.municipalityFilter.value=old};
/** Carga datos y garantiza ocultar loader. */const load=async()=>{e.loader.classList.remove('d-none');e.wrapper.classList.add('d-none');e.empty.classList.add('d-none');hideError();try{const [data]=await Promise.all([fetchCommunities(),loadParishes()]);communities=data;municipalities();page=1;render()}catch(x){console.error('No fue posible cargar comunidades:',x);communities=[];e.emptyText.textContent='No fue posible cargar las comunidades.';e.empty.classList.remove('d-none');showError(errorText(x))}finally{e.loader.classList.add('d-none')}};
/** Devuelve registros que cumplen búsqueda y filtros combinados. */const filtered=()=>{const q=e.search.value.trim().toLocaleLowerCase('es');return communities.filter(x=>[x.codigo,x.nombre,x.tipo,x.parroquia,x.parroquia_codigo,x.municipio,x.responsable,x.telefono,x.correo].some(v=>v?.trim().toLocaleLowerCase('es').includes(q))&&(!e.parishFilter.value||x.parroquia_id===e.parishFilter.value)&&(!e.typeFilter.value||x.tipo===e.typeFilter.value)&&(!e.municipalityFilter.value||x.municipio===e.municipalityFilter.value)&&(e.statusFilter.value===''||String(x.estado)===e.statusFilter.value))};
const button=(icon,label,fn)=>{const b=document.createElement('button'),i=document.createElement('i');b.className='btn community-action';b.type='button';b.setAttribute('aria-label',label);i.className=`bi ${icon}`;b.append(i);b.addEventListener('click',fn);return b};
/** Renderiza una fila con acciones permitidas. */const row=(x)=>{const tr=document.createElement('tr');[x.codigo,x.nombre,x.tipo,x.parroquia||'—',x.municipio,x.responsable||'—'].forEach((v,n)=>{const td=document.createElement('td');td.textContent=v;if(n===1)td.className='community-table__name';tr.append(td)});const state=document.createElement('td'),badge=document.createElement('span');badge.className=`community-badge ${x.estado?'community-badge--active':'community-badge--inactive'}`;badge.textContent=x.estado?'Activa':'Inactiva';state.append(badge);tr.append(state);const td=document.createElement('td'),group=document.createElement('div');group.className='community-actions';group.append(button('bi-eye',`Ver ${x.nombre}`,()=>details(x)));if(hasPermission(context,'communities.update')){group.append(button('bi-pencil',`Editar ${x.nombre}`,()=>edit(x)));group.append(button(x.estado?'bi-pause-circle':'bi-play-circle',x.estado?'Inactivar':'Reactivar',()=>change(x)))}td.append(group);tr.append(td);e.table.append(tr)};
/** Renderiza tabla, estado vacío y paginación local. */const render=()=>{const data=filtered(),pages=Math.max(1,Math.ceil(data.length/PAGE_SIZE));page=Math.min(page,pages);e.count.textContent=`${data.length} ${data.length===1?'registro':'registros'}`;e.table.replaceChildren();data.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE).forEach(row);e.wrapper.classList.toggle('d-none',data.length===0);e.empty.classList.toggle('d-none',data.length>0);e.pagination.replaceChildren();e.pagination.classList.toggle('d-none',pages<=1);for(let p=1;p<=pages;p+=1){const b=document.createElement('button');b.textContent=p;b.classList.toggle('is-active',p===page);b.addEventListener('click',()=>{page=p;render()});e.pagination.append(b)}};
/** Restablece el formulario para creación. */const reset=()=>{editingId=null;e.form.reset();e.form.classList.remove('was-validated');e.form.elements.tipo.value='Comunidad';e.form.elements.estado.value='true';e.title.textContent='Nueva comunidad';e.save.querySelector('span').textContent='Guardar';codeMode()};
const newCommunity=()=>{if(!hasPermission(context,'communities.create'))return showToast('Acceso no autorizado.',false);reset();formModal.show()};
/** Precarga formulario para Administrador. */const edit=(x)=>{if(!hasPermission(context,'communities.update'))return showToast('Acceso no autorizado.',false);editingId=x.id;e.form.reset();Object.entries(x).forEach(([k,v])=>{const f=e.form.elements.namedItem(k);if(f)f.value=k==='estado'?String(v):v??''});codeMode(x.codigo);e.title.textContent='Editar comunidad';e.save.querySelector('span').textContent='Guardar cambios';formModal.show()};
/** Muestra detalle sin UUIDs. */const details=(x)=>{const values=[['Código',x.codigo],['Nombre',x.nombre],['Tipo',x.tipo],['Parroquia',x.parroquia],['Código de parroquia',x.parroquia_codigo],['Dirección',x.direccion],['Municipio',x.municipio],['Responsable',x.responsable],['Teléfono',x.telefono],['Correo',x.correo],['Fecha de creación',date(x.fecha_creacion)],['Estado',x.estado?'Activa':'Inactiva'],['Observaciones',x.observaciones],['Fecha de registro',date(x.created_at,true)],['Última actualización',date(x.updated_at,true)]];e.detail.replaceChildren();const dl=document.createElement('dl');dl.className='community-details';values.forEach(([a,b])=>{const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=a;dd.textContent=b||'—';dl.append(dt,dd)});e.detail.append(dl);detailModal.show()};
const change=(x)=>{if(!hasPermission(context,'communities.update'))return showToast('Acceso no autorizado.',false);pending={id:x.id,estado:!x.estado};const action=x.estado?'Inactivar':'Reactivar';e.statusTitle.textContent=`${action} comunidad`;e.statusMessage.textContent=`¿Desea ${action.toLowerCase()} la comunidad “${x.nombre}”?`;e.confirm.querySelector('span').textContent=action;statusModal.show()};
const payload=()=>{const d=new FormData(e.form);return{parroquia_id:d.get('parroquia_id'),nombre:d.get('nombre').trim(),tipo:d.get('tipo'),direccion:optional(d.get('direccion')),municipio:d.get('municipio').trim(),responsable:optional(d.get('responsable')),telefono:optional(d.get('telefono')),correo:optional(d.get('correo')),fecha_creacion:d.get('fecha_creacion')||null,observaciones:optional(d.get('observaciones')),estado:d.get('estado')==='true'}};
/** Guarda creación o edición con filtro obligatorio por id. */const save=async(ev)=>{ev.preventDefault();if(!hasPermission(context,editingId?'communities.update':'communities.create'))return showToast('Acceso no autorizado.',false);if(!e.form.checkValidity()){e.form.classList.add('was-validated');showError('Complete los campos obligatorios y revise el correo electrónico.');return}const data=payload(),editing=Boolean(editingId);e.save.disabled=true;e.save.querySelector('.spinner-border').classList.remove('d-none');try{const query=editing?supabase.from('comunidades').update(data).eq('id',editingId).select().single():supabase.from('comunidades').insert(data).select().single();const {data,error}=await query;if(error)throw error;formModal.hide();reset();await load();showToast(editing?'Comunidad actualizada correctamente.':`Comunidad ${data.codigo} registrada correctamente.`)}catch(x){console.error('No fue posible guardar comunidad:',x);showError(errorText(x));showToast(errorText(x),false)}finally{e.save.disabled=false;e.save.querySelector('.spinner-border').classList.add('d-none')}};
/** Actualiza únicamente el estado sin borrar historial. */const confirm=async()=>{if(!pending||!hasPermission(context,'communities.update'))return showToast('Acceso no autorizado.',false);e.confirm.disabled=true;try{const {error}=await supabase.from('comunidades').update({estado:pending.estado}).eq('id',pending.id).select().single();if(error)throw error;statusModal.hide();await load();showToast(pending.estado?'Comunidad reactivada correctamente.':'Comunidad inactivada correctamente.')}catch(x){console.error('No fue posible cambiar estado:',x);showError(errorText(x));showToast(errorText(x),false)}finally{pending=null;e.confirm.disabled=false}};
/** Precarga municipio de la parroquia seleccionada sin impedir cambios manuales. */const syncMunicipality=()=>{const p=parishes.find(x=>x.id===e.parish.value);if(p)e.municipality.value=p.municipio||''};
/** Inicializa el módulo tras montar la plantilla dinámica. */export async function initComunidades(user){if(!user||!hasPermission(user,'communities.view'))return;destroyComunidades();context=user;mount();e=cache();const bs=bootstrap();formModal=bs.Modal.getOrCreateInstance(document.querySelector('#community-modal'));detailModal=bs.Modal.getOrCreateInstance(document.querySelector('#community-detail-modal'));statusModal=bs.Modal.getOrCreateInstance(document.querySelector('#community-status-modal'));toast=bs.Toast.getOrCreateInstance(document.querySelector('#community-toast'));events=new AbortController();const o={signal:events.signal};document.querySelector('#new-community-button').hidden=!hasPermission(context,'communities.create');document.querySelector('#new-community-button').addEventListener('click',newCommunity,o);e.form.addEventListener('submit',save,o);e.parish.addEventListener('change',syncMunicipality,o);[e.search,e.parishFilter,e.typeFilter,e.municipalityFilter,e.statusFilter].forEach(c=>c.addEventListener(c===e.search?'input':'change',()=>{page=1;render()},o));e.confirm.addEventListener('click',confirm,o);await load()}
/** Limpia eventos, Bootstrap y overlays al salir de Comunidades. */export const destroyComunidades=()=>{events?.abort();[formModal,detailModal,statusModal,toast].forEach(x=>x?.dispose());document.querySelectorAll('[data-view-overlay="comunidades"]').forEach(x=>x.remove())};
