/** Vista de solo lectura para las fichas integrales; RLS filtra cada consulta. */
import { supabase, hasPermission } from './auth.js';
/** Registra diagnóstico temporal sin incluir tokens ni datos sensibles. */
const logQuery = (viewName, result) => {
  console.info('Vista consultada:', viewName);
  console.info('Cantidad de registros:', result?.data?.length ?? 0);
  if (result?.error) console.error('Error Supabase:', result.error);
};
let e, context, request=0, controller;
const isSecretary=()=>context?.role?.nombre==='Secretario';const assignedParishId=()=>isSecretary()?context.profile?.parroquia_id:null;
const priestPhotoUrls=new Map();
const priestPhoto=async path=>{if(!path)return null;if(priestPhotoUrls.has(path))return priestPhotoUrls.get(path);const {data,error}=await supabase.storage.from('sacerdotes-fotos').createSignedUrl(path,3600);if(error)throw error;priestPhotoUrls.set(path,data.signedUrl);return data.signedUrl};
const profilePhoto=async(priest)=>{const wrap=node('div',undefined,'priest-profile-photo priest-profile-photo--fallback');if(!priest.foto_path){wrap.textContent='Sin fotografía';return wrap}try{const img=document.createElement('img');img.className='priest-profile-photo';img.alt=`Fotografía de ${priest.nombre_completo}`;img.src=await priestPhoto(priest.foto_path);img.onerror=()=>{wrap.className='priest-profile-photo priest-profile-photo--fallback';wrap.replaceChildren(document.createTextNode('Sin fotografía'))};return img}catch(error){console.error('No fue posible generar la URL firmada de la fotografía:',error);wrap.textContent='Sin fotografía';return wrap}};
const waitForImage=async img=>{if(!img||img.complete)return;await new Promise(resolve=>{img.addEventListener('load',resolve,{once:true});img.addEventListener('error',resolve,{once:true})})};
const q=(table,filter,value)=>{let x=supabase.from(table).select('*');return value?x.eq(filter,value):x};
const date=v=>v?new Intl.DateTimeFormat('es-GT').format(new Date(`${v}T00:00:00`)):'—';
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
const cache=()=>({parish:eid('consultas-parish-select'),deanery:eid('consultas-deanery-filter'),priest:eid('consultas-priest-select'),parishInactive:eid('consultas-parish-inactive'),priestInactive:eid('consultas-priest-inactive'),parishEmpty:eid('consultas-parish-empty'),priestEmpty:eid('consultas-priest-empty'),parishSheet:eid('consultas-parish-sheet'),priestSheet:eid('consultas-priest-sheet'),error:eid('consultas-error')});const eid=id=>document.getElementById(id);
const error=x=>{e.error.textContent='No fue posible cargar una parte de la ficha. Intente nuevamente.';e.error.classList.remove('d-none');console.error(x)};
const select=(el,data,label,full)=>{const old=el.value;el.replaceChildren(new Option(label,''));data.forEach(x=>el.add(new Option(`${x.codigo} · ${full(x)}`,x.id)));el.value=old};
const loadSelectors=async()=>{try{const [p,s]=await Promise.all([supabase.from('v_ficha_parroquias').select('id,codigo,nombre,estado,decanato_id,decanato_codigo,decanato').order('nombre'),supabase.from('v_ficha_sacerdotes').select('id,codigo,nombre_completo,activo').order('nombre_completo')]);if(p.error)throw p.error;if(s.error)throw s.error;const parishes=p.data??[];if(e.deanery){const old=e.deanery.value;e.deanery.replaceChildren(new Option('Todos los decanatos',''));[...new Map(parishes.filter(x=>x.decanato_id).map(x=>[x.decanato_id,{codigo:x.decanato_codigo,nombre:x.decanato}])).entries()].forEach(([id,x])=>e.deanery.add(new Option(`${x.codigo} · ${x.nombre}`,String(id))));e.deanery.value=old}const visibleParishes=isSecretary()?parishes.filter(x=>String(x.id)===String(assignedParishId())):parishes.filter(x=>(e.parishInactive.checked||x.estado)&&(!e.deanery?.value||String(x.decanato_id)===e.deanery.value));select(e.parish,visibleParishes,'Seleccione una parroquia',x=>x.nombre);if(isSecretary()){const parish=visibleParishes[0];if(!parish){e.parishEmpty.textContent='No se encontraron registros disponibles para este usuario.';e.parishEmpty.classList.remove('d-none');return false}e.parish.value=parish.id;const label=eid('consultas-my-parish-label');if(label)label.textContent=`${parish.codigo} · ${parish.nombre}`}select(e.priest,(s.data??[]).filter(x=>e.priestInactive.checked||x.activo),'Seleccione un sacerdote',x=>x.nombre_completo);return true}catch(x){error(x);return false}};
const section=(title)=>{const x=node('section',undefined,'consultas-section');x.append(node('h2',title));return x};const cards=items=>{const g=node('div',undefined,'consultas-grid');items.forEach(([l,v])=>{const c=node('div',undefined,'consultas-card');c.append(node('span',l),node('strong',String(v??0)));g.append(c)});return g};
const info=(data,fields)=>{const dl=node('dl','');fields.forEach(([l,k])=>{dl.append(node('dt',l),node('dd',k.includes('fecha')?date(data[k]):data[k]??'—'))});return dl};
const table=(headers,items,render)=>{const wrap=node('div',undefined,'table-responsive'),t=node('table',undefined,'table consultas-table'),head=node('thead'),r=node('tr'),body=node('tbody');headers.forEach(h=>r.append(node('th',h)));head.append(r);items.forEach(x=>body.append(render(x)));t.append(head,body);wrap.append(t);return wrap};
const link=(text,fn)=>{const b=node('button',text,'consultas-link');b.type='button';b.addEventListener('click',fn);return b};
const parishRow=x=>{const r=node('tr');[x.codigo,x.nombre,x.tipo,x.municipio,x.responsable,x.estado?'Activa':'Inactiva'].forEach(v=>r.append(node('td',v??'—')));return r};
const showParish=async id=>{if(isSecretary()&&String(id)!==String(assignedParishId()))return;const token=++request;e.parishEmpty.classList.add('d-none');e.parishSheet.classList.remove('d-none');e.parishSheet.replaceChildren(node('p','Cargando ficha integral...'));const all=await Promise.allSettled([q('v_ficha_parroquias','id',id),q('v_asignaciones_sacerdotales','parroquia_id',id),q('v_comunidades','parroquia_id',id),q('v_capillas','parroquia_id',id),q('v_inventario_documental','parroquia_id',id)]);if(token!==request)return;const result=all.map(x=>x.status==='fulfilled'?(x.value.data??[]):[]);const [f,assign,communities,chapels,docs]=result;if(!f[0])return error(all[0]);const p=f[0],sheet=e.parishSheet;sheet.replaceChildren(node('h2',`${p.codigo} · ${p.nombre}`),node('p',`${p.patrono??'Sin patrono'} · ${p.municipio} · ${p.estado?'Activa':'Inactiva'}`),cards([['Movimientos y Pastorales',p.total_comunidades],['Comunidades con oratorios',p.total_capillas],['Sacerdotes asignados',p.total_sacerdotes_asignados],['Documentos',p.total_documentos],['Documentos por restaurar',p.documentos_por_restaurar]]));let s=section('Información general');s.append(info(p,[['Código','codigo'],['Patrono','patrono'],['Dirección','direccion'],['Municipio','municipio'],['Departamento','departamento'],['Teléfono','telefono'],['Correo','correo'],['Fecha de fundación','fecha_fundacion'],['Observaciones','observaciones']]));sheet.append(s);s=section('Sacerdotes asignados');s.append(table(['Sacerdote','Código','Cargo','Inicio','Fin','Estado'],assign,x=>{const r=node('tr'),td=node('td');td.append(link(x.sacerdote,()=>openPriest(x.sacerdote_id)));r.append(td,node('td',x.sacerdote_codigo),node('td',x.cargo),node('td',date(x.fecha_inicio)),node('td',date(x.fecha_fin)),node('td',x.estado_asignacion));return r}));sheet.append(s);s=section('Movimientos y Pastorales');s.append(table(['Código','Nombre','Tipo','Municipio','Responsable','Estado'],communities,parishRow));sheet.append(s);s=section('Comunidades con oratorios');s.append(table(['Código','Nombre','Tipo','Movimiento o Pastoral','Municipio','Responsable','Estado'],chapels,x=>{const r=node('tr');[x.codigo,x.nombre,x.tipo,x.comunidad||'Dependencia directa',x.municipio,x.responsable,x.estado?'Activa':'Inactiva'].forEach(v=>r.append(node('td',v??'—')));return r}));sheet.append(s);s=section('Inventario documental');s.append(table(['Código','Tipo','Título','Movimiento o Pastoral','Comunidad con oratorio','Ubicación','Conservación','Restauración','Estado'],docs,x=>{const r=node('tr');[x.codigo,x.tipo_documento,x.titulo,x.comunidad,x.capilla,x.ubicacion_fisica,x.estado_conservacion,x.requiere_restauracion?'Sí':'No',x.estado?'Activo':'Inactivo'].forEach(v=>r.append(node('td',v??'—')));return r}));sheet.append(s)};
const showPriest=async id=>{const token=++request;e.priestEmpty.classList.add('d-none');e.priestSheet.classList.remove('d-none');e.priestSheet.replaceChildren(node('p','Cargando ficha integral...'));const all=await Promise.allSettled([q('v_ficha_sacerdotes','id',id),q('v_asignaciones_sacerdotales','sacerdote_id',id)]);if(token!==request)return;const [a,b]=all.map(x=>x.status==='fulfilled'?(x.value.data??[]):[]);if(!a[0])return error(all[0]);const p=a[0],unique=new Set(b.map(x=>x.parroquia_id)).size,years=p.fecha_ordenacion?Math.floor((Date.now()-new Date(p.fecha_ordenacion))/31557600000):'—',sheet=e.priestSheet,hero=node('header',undefined,'priest-profile-header'),copy=node('div');copy.append(node('strong',`${p.codigo} · ${p.nombre_completo}`),node('span',`${p.tipo_clero} · ${p.congregacion||'Sin congregación'} · ${p.estado_ministerial}`));hero.append(await profilePhoto(p),copy);if(token!==request)return;sheet.replaceChildren(hero,cards([['Total de asignaciones',p.total_asignaciones],['Asignaciones vigentes',p.asignaciones_vigentes],['Años desde ordenación',years],['Parroquias atendidas',unique]]));let s=section('Información personal y ministerial');s.append(info(p,[['Nombres','nombres'],['Apellidos','apellidos'],['Nombre religioso','nombre_religioso'],['Fecha de nacimiento','fecha_nacimiento'],['Fecha de ordenación','fecha_ordenacion'],['Congregación','congregacion'],['Nacionalidad','nacionalidad'],['Teléfono','telefono'],['Correo','correo'],['Dirección','direccion'],['Observaciones','observaciones']]));sheet.append(s);s=section('Historial de asignaciones');s.append(table(['Parroquia','Código','Municipio','Cargo','Inicio','Fin','Estado'],b.sort((x,y)=>String(y.fecha_inicio).localeCompare(String(x.fecha_inicio))).map(x=>x),x=>{const r=node('tr'),td=node('td');td.append(link(x.parroquia,()=>openParish(x.parroquia_id)));r.append(td,node('td',x.parroquia_codigo),node('td',x.municipio),node('td',x.cargo),node('td',date(x.fecha_inicio)),node('td',date(x.fecha_fin)),node('td',x.estado_asignacion));return r}));sheet.append(s)};
const openParish=id=>{if(isSecretary()&&String(id)!==String(assignedParishId()))return;document.querySelector('[data-bs-target="#consultas-parishes"]').click();e.parish.value=id;showParish(id)};const openPriest=id=>{document.querySelector('[data-bs-target="#consultas-priests"]').click();e.priest.value=id;showPriest(id)};
const ensureDeaneryFilter=()=>{if(isSecretary()||eid('consultas-deanery-filter'))return;const select=document.createElement('select');select.id='consultas-deanery-filter';select.className='form-select';select.setAttribute('aria-label','Filtrar parroquias por decanato');select.append(new Option('Todos los decanatos',''));eid('consultas-parish-select').before(select)};
/** Reemplaza los controles parroquiales por la parroquia única disponible para Secretario. */const showMyParish=()=>{if(!isSecretary())return;const selector=e.parish.closest('.consultas-selector');e.parish.classList.add('d-none');e.parishInactive.closest('label')?.classList.add('d-none');let summary=eid('consultas-my-parish');if(!summary){summary=node('div',undefined,'consultas-assigned-parish');summary.id='consultas-my-parish';summary.append(node('span','Mi parroquia'),node('strong',undefined));selector.prepend(summary)}const label=summary.querySelector('strong');label.id='consultas-my-parish-label';label.textContent=context.assignedParish?`${context.assignedParish.codigo} · ${context.assignedParish.nombre}`:'Parroquia asignada'};
export async function initConsultas(user){if(!user||!hasPermission(user,'consultas.view'))return;context=user;ensureDeaneryFilter();e=cache();if(isSecretary()&&!assignedParishId()){e.parishEmpty.textContent='Su usuario no tiene una parroquia asignada. Contacte al Administrador.';e.parishEmpty.classList.remove('d-none');return}showMyParish();eid('consultas-generated-date').textContent=new Intl.DateTimeFormat('es-GT',{dateStyle:'long'}).format(new Date());e.parish.addEventListener('change',()=>e.parish.value?showParish(e.parish.value):(e.parishEmpty.classList.remove('d-none'),e.parishSheet.classList.add('d-none')));e.priest.addEventListener('change',()=>e.priest.value?showPriest(e.priest.value):(e.priestEmpty.classList.remove('d-none'),e.priestSheet.classList.add('d-none')));e.deanery?.addEventListener('change',loadSelectors);e.parishInactive.addEventListener('change',loadSelectors);e.priestInactive.addEventListener('change',loadSelectors);eid('consultas-print').addEventListener('click',async()=>{await waitForImage(e.priestSheet.querySelector('img.priest-profile-photo'));window.print()});const loaded=await loadSelectors();if(isSecretary()&&loaded)await showParish(assignedParishId())};export const destroyConsultas=()=>{controller?.abort()};
