/** Interfaz de Usuarios: todas las operaciones se delegan a admin-users. */
import { supabase, hasPermission } from './auth.js';
let e, users=[], selected=null, mode='create', formModal, confirmModal, toast, pendingAction, events;
const login=()=>window.location.replace(new URL('../index.html',import.meta.url));
const alert=m=>{e.alert.textContent=m;e.alert.classList.remove('d-none')};const hideAlert=()=>e.alert.classList.add('d-none');const notify=(m,ok=true)=>{e.toastMessage.textContent=m;e.toastIcon.className=`bi ${ok?'bi-check-circle-fill':'bi-exclamation-circle-fill'}`;toast.show()};
const cache=()=>({alert:document.querySelector('#users-alert'),summary:document.querySelector('#users-summary'),loader:document.querySelector('#users-loader'),table:document.querySelector('#users-table'),form:document.querySelector('#user-form'),title:document.querySelector('#user-modal-title'),save:document.querySelector('#user-save'),emailGroup:document.querySelector('#user-email-group'),passwordGroup:document.querySelector('#user-password-group'),activeGroup:document.querySelector('#user-active-group'),password:document.querySelector('#user-password'),togglePassword:document.querySelector('#toggle-user-password'),confirmTitle:document.querySelector('#user-confirm-title'),confirmMessage:document.querySelector('#user-confirm-message'),confirmButton:document.querySelector('#user-confirm-button'),toastMessage:document.querySelector('#users-toast-message'),toastIcon:document.querySelector('#users-toast-icon')});
const invoke=async(body)=>{const {data,error}=await supabase.functions.invoke('admin-users',{body});if(error){const status=error.context?.status;let payload;try{payload=await error.context?.clone?.().json()}catch{}const network=!status;const message=network?'No fue posible comunicarse con el servicio de usuarios.':payload?.error?.message??error.message;console.error('admin-users', { action: body.action, type: error.name, status });if(status===401)login();throw new Error(message)}if(!data?.ok)throw new Error(data?.error?.message??'No fue posible completar la operación.');return data.data};
const cell=v=>{const td=document.createElement('td');td.textContent=v??'—';return td};
const action=(icon,title,modifier,handler)=>{const b=document.createElement('button'),i=document.createElement('i');b.className=`btn user-action-button ${modifier}`;b.type='button';b.title=title;b.setAttribute('aria-label',title);i.className=`bi ${icon}`;i.setAttribute('aria-hidden','true');b.append(i);b.addEventListener('click',handler);return b};
const render=()=>{e.table.replaceChildren();users.forEach(u=>{const r=document.createElement('tr'),actions=document.createElement('td'),group=document.createElement('div');group.className='user-actions';group.append(action('bi-pencil-square',`Editar perfil de ${u.nombre_completo}`,'',()=>openEdit(u,'profile')),action('bi-person-badge',`Cambiar rol de ${u.nombre_completo}`,'user-action-button--role',()=>openEdit(u,'role')),action(u.activo?'bi-person-slash':'bi-person-check',`${u.activo?'Inactivar':'Activar'} a ${u.nombre_completo}`,u.activo?'user-action-button--danger':'user-action-button--active',()=>confirmStatus(u)),action('bi-key',`Restablecer contraseña de ${u.nombre_completo}`,'user-action-button--password',()=>openEdit(u,'password')));actions.append(group);r.append(cell(u.nombre_completo),cell(u.email),cell(u.rol),cell(u.activo?'Activo':'Inactivo'),cell(u.created_at?new Intl.DateTimeFormat('es-GT').format(new Date(u.created_at)):'—'),actions);e.table.append(r)});const stats=[['Total de usuarios',users.length],['Administradores activos',users.filter(u=>u.rol_id==='1'&&u.activo).length],['Usuarios activos',users.filter(u=>u.activo).length],['Usuarios inactivos',users.filter(u=>!u.activo).length]];e.summary.replaceChildren(...stats.map(([l,n])=>{const d=document.createElement('div');d.className='inventory-summary__card';d.append(cell(l).firstChild,Object.assign(document.createElement('strong'),{textContent:String(n)}));return d}))};
export async function cargarUsuarios(){e.loader.classList.remove('d-none');hideAlert();try{const {data:{session}}=await supabase.auth.getSession();if(!session)return login();const data=await invoke({action:'list',page:1,perPage:100});users=data.users??[];render()}catch(x){console.error('Usuarios:',x.message);alert(x.message)}finally{e.loader.classList.add('d-none')}};
const reset=()=>{selected=null;mode='create';e.form.reset();e.form.classList.remove('was-validated');e.title.textContent='Nuevo usuario';e.emailGroup.hidden=false;e.passwordGroup.hidden=false;e.activeGroup.hidden=false;e.form.elements.email.required=true;e.password.required=true;e.form.elements.rol_id.value='2'};
const openNew=()=>{reset();formModal.show()};
const openEdit=(user,nextMode)=>{selected=user;mode=nextMode;e.form.reset();e.form.classList.remove('was-validated');e.form.elements.nombre.value=user.nombre;e.form.elements.apellido.value=user.apellido;e.form.elements.rol_id.value=user.rol_id;e.emailGroup.hidden=true;e.activeGroup.hidden=true;e.passwordGroup.hidden=nextMode!=='password';e.form.elements.email.required=false;e.password.required=nextMode==='password';e.title.textContent=nextMode==='profile'?'Editar perfil':nextMode==='role'?'Cambiar rol':'Restablecer contraseña temporal';formModal.show()};
const submit=async ev=>{ev.preventDefault();const raw=e.password.value;const passwordMode=mode==='create'||mode==='password';const passwordValid=!passwordMode||(/(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[^A-Za-z0-9]).{10,}/.test(raw));if(!e.form.checkValidity()||!passwordValid){e.form.classList.add('was-validated');if(!passwordValid)alert('La contraseña debe tener mínimo 10 caracteres, mayúscula, minúscula, número y carácter especial.');return}e.save.disabled=true;e.save.querySelector('.spinner-border').classList.remove('d-none');try{const d=new FormData(e.form);let body;if(mode==='create')body={action:'create',nombre:d.get('nombre').trim(),apellido:d.get('apellido').trim(),email:d.get('email').trim(),rol_id:d.get('rol_id'),password:d.get('password'),activo:d.get('activo')==='on'};if(mode==='profile')body={action:'updateProfile',userId:selected.id,nombre:d.get('nombre').trim(),apellido:d.get('apellido').trim()};if(mode==='role')body={action:'changeRole',userId:selected.id,rol_id:d.get('rol_id')};if(mode==='password')body={action:'resetPassword',userId:selected.id,password:d.get('password')};await invoke(body);formModal.hide();notify(mode==='create'?'Usuario creado correctamente.':'Usuario actualizado correctamente.');reset();await cargarUsuarios()}catch(x){alert(x.message)}finally{e.save.disabled=false;e.save.querySelector('.spinner-border').classList.add('d-none')}};
const confirmStatus=user=>{selected=user;pendingAction=async()=>{await invoke({action:user.activo?'deactivate':'activate',userId:user.id});confirmModal.hide();notify(user.activo?'Usuario inactivado correctamente.':'Usuario activado correctamente.');await cargarUsuarios()};e.confirmTitle.textContent=user.activo?'Inactivar usuario':'Activar usuario';e.confirmMessage.textContent=`¿Desea ${user.activo?'inactivar':'activar'} a ${user.nombre_completo}?`;confirmModal.show()};
export async function initUsuarios(context){if(!hasPermission(context,'users.view'))return;e=cache();formModal=bootstrap.Modal.getOrCreateInstance(document.querySelector('#user-modal'));confirmModal=bootstrap.Modal.getOrCreateInstance(document.querySelector('#user-confirm-modal'));toast=bootstrap.Toast.getOrCreateInstance(document.querySelector('#users-toast'));events=new AbortController();const o={signal:events.signal};document.querySelector('#new-user').addEventListener('click',openNew,o);e.form.addEventListener('submit',submit,o);e.togglePassword.addEventListener('click',()=>{e.password.type=e.password.type==='password'?'text':'password'},o);e.confirmButton.addEventListener('click',async()=>{e.confirmButton.disabled=true;try{await pendingAction?.()}catch(x){alert(x.message)}finally{e.confirmButton.disabled=false}},o);await cargarUsuarios()};export const destroyUsuarios=()=>{events?.abort();formModal?.dispose();confirmModal?.dispose();toast?.dispose()};
